name: trukk_manager
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  trukk_driver:
         path: ../trukk_driver
  trukk_requester:
         path: ../trukk_requester
  
  cupertino_icons: ^1.0.2
  flutter_windowmanager:
  equatable:
  flex_color_scheme:
  states_rebuilder:
  flutter_command: ^5.0.0+4
  get_it_mixin: ^4.2.0
  get_it:
  hive_flutter:
  uuid:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
